dataset:
  type: imagenet_test
  transforms:
    type: imagenet256x256

arch:
  stage : 2
  stage_1: 
    target: rqvae.models.MAE.Stage1MAE
    params:
      ckpt_path: '/home/bytetriper/model_zoo/mae_base_256'
    checkpointing: false
  stage_2:
    target:  rqvae.models.dummy.dummy_model_stage2
    params:
      hidden_size: 768
  ema: 0.114514
optimizer:
  type: adamW
  init_lr: 0.0005
  weight_decay: 0.0001
  betas: [0.9, 0.95]
  warmup:
    epoch: 0
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.0
    mode: fix
    start_from_zero: True
  max_gn: 1.0

experiment:
  batch_size: 2
  total_batch_size: 8
  epochs: 2
  save_ckpt_freq: 2
  test_freq: 2
  amp: false
