dataset:
  type: imagenet
  transforms:
    type: imagenetVAE256x256
arch:
  stage: 1
  stage_1:
    target: rqvae.models.ldm.AutoEncoderKL_Stage1
    params:
      embed_dim: 16
      kl_weight: 1.0e-06
      ddconfig:
        double_z: true
        z_channels: 16
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult:
        - 1
        - 1
        - 2
        - 2
        - 4
        num_res_blocks: 2
        attn_resolutions:
        - 16
        dropout: 0.0
  checkpointing: false
  ema: 0.9999
experiment:
  batch_size: 1
  epochs: 6
  accu_step: 1
  save_ckpt_freq: 6
  test_freq: 1
  amp: false
  actual_batch_size: 256

optimizer:
  # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
  type: adam
  init_lr: 8.0e-5
  weight_decay: 0.0
  betas: [0.5, 0.9]
  max_gn: None
  amp: true
  warmup:
    epoch: 0.5
    multiplier: 1
    buffer_epoch: 0
    min_lr: 8.0e-5 # no decay
    mode: fix
    start_from_zero: false

gan:
  disc:
    arch:
      in_channels: 3
      num_layers: 3
      use_actnorm: false
      ndf: 64
      spectral_norm: false
    optimizer:
      # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
      type: adam
      init_lr: 8.0e-5
      weight_decay: 0.0
      betas: [0.5, 0.9]
      max_gn: None
      amp: true
      warmup:
        epoch: 0.5
        multiplier: 1
        buffer_epoch: 0
        min_lr: 8.0e-5 # no decay
        mode: fix
        start_from_zero: false

    experiment:
      test_freq: 1
      amp: false
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: .5
    perceptual_weight: 1.0
    disc_start: 3
    disc_upd_start: 3
    lpips_start: 0