dataset:
  type: imagenet_overfit
  transforms:
    type: imagenet256x256
arch:
  stage: 2
  stage_1:
    target: rqvae.models.identity.Identity_Stage1
    params:
      hidden_dim: 3
      input_size: 256
      in_channels: 3
    checkpointing: false
  stage_2:
    target: rqvae.models.DiT.DiT_Stage2
    params:
      # DiT B/1 Recipe
      hidden_size: 768
      input_size: 256
      patch_size: 4
      depth: 2
      num_heads: 12
      num_classes: 1000
      cfg: 0.0
      in_channels: 3
      learn_sigma: true
      noise_schedule: 'linear'
      inference_step: 250
      n_samples: 1
      class_cls_str: 'rqvae.models.DiT.models.DiTWideAtLast'
      second_patch_size: 16
      second_depth: 1
      second_hidden_size: 780
    checkpointing: false
  ema: 0.114514
optimizer:
  # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
  type: adamw
  init_lr: 2.0e-4
  weight_decay: 0.0
  betas: [0.9, 0.95]
  max_gn: None
  amp: true
  warmup:
    epoch: 1
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.
    mode: fix
    start_from_zero: false

experiment:
  batch_size: 1
  accu_step: 1
  epochs: 3
  save_ckpt_freq: 1000
  test_freq: 1
  amp: false
