dataset:
  type: imagenet
  transforms:
    type: imagenet256x256

arch:
  stage: 1
  target: rqvae.models.MAE.Stage1MAE
  params:
    ckpt_path: './ckpt_gcs/model_zoo/mae_base_256'
    mask_ratio: .75
    train_encoder: true
  checkpointing: false
  ema: 0.114514
optimizer:
  # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
  type: adamw
  init_lr: .0
  weight_decay: 0.0
  betas: [0.9, 0.95]
  max_gn: None
  warmup:
    epoch: 10  # 10% of total epochs
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.
    mode: fix
    start_from_zero: true

experiment:
  batch_size: 125
  accu_step: 1 # total bsz of 4096 on a 128 pod
  epochs: 1
  save_ckpt_freq: 20
  test_freq: 5
  amp: false

gan:
  disc:
    arch:
      in_channels: 3
      num_layers: 2
      use_actnorm: false
      ndf: 64
      spectral_norm: false
    optimizer:
      # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
      type: adamw
      init_lr: 1.0e-3
      weight_decay: 0.0
      betas: [0.9, 0.95]
      max_gn: None
      warmup:
        epoch: 5  # 5% of total epochs
        multiplier: 1
        buffer_epoch: 0
        min_lr: 0.
        mode: fix
        start_from_zero: true
    experiment:
      test_freq: 1
      amp: false
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: .75
    perceptual_weight: 0.
    disc_start: 100000