dataset:
  type: imagenet_recon
  transforms:
    type: imagenet256x256

arch:
  stage: 1
  target: rqvae.models.MAE.Stage1MAE
  params:
    ckpt_path: '/home/bytetriper/model_zoo/mae_base_256'
    no_cls: true
  checkpointing: false
  ema: 0.114514
optimizer:
  # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
  type: adamw
  init_lr: 0.0
  weight_decay: 0.0
  betas: [0.9, 0.95]
  max_gn: None
  warmup:
    epoch: 1  # 5% of total epochs
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.
    mode: fix
    start_from_zero: true

experiment:
  batch_size: 125 # so it can divide 50000
  epochs: 1
  accu_step: 1
  save_ckpt_freq: 1000
  test_freq: 1
  amp: false

gan:
  disc:
    arch:
      in_channels: 3
      num_layers: 2
      use_actnorm: false
      ndf: 64
      spectral_norm: false
    optimizer:
      # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
      type: adamw
      init_lr: 4.0e-5
      weight_decay: 0.0
      betas: [0.5, 0.9]
      max_gn: None
      warmup:
        epoch: 1  # 5% of total epochs
        multiplier: 1
        buffer_epoch: 0
        min_lr: 0.
        mode: linear
        start_from_zero: true
    experiment:
      test_freq: 1
      amp: false
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: .75
    perceptual_weight: 0.0
    disc_start: 0