dataset:
  type: imagenet
  transforms:
    type: imagenetDiT256x256

arch:
  stage: 2
  stage_1:
    target: rqvae.models.MAE.Stage1MAEwConvNextDCAE
    params:
      ckpt_path: './ckpt_gcs/model_zoo/mae_base_256_d16_h8'
      no_cls: true
      do_decoder_embed_in_encode: true
      up_layers_channels: [ 48, 192, 768]
      down_layers_channels: [192,48,16]
      down_depths: [3, 3, 3]
      up_depths: [3, 3]
  connector:
    target: rqvae.models.connectors.ReshapeAndSplit_connector
    params:
      split: 1
      remove_cls: true
  stage_2:
    target: rqvae.models.DiT.DiT_Stage2
    params:
      # DiT B/1 Recipe
      hidden_size: 768
      input_size: 16
      patch_size: 1
      depth: 12
      num_heads: 12
      num_classes: 1000
      cfg: 0.0
      in_channels: 16
      learn_sigma: true
      noise_schedule: 'linear'
      inference_step: 250
  checkpointing: false
  ema: 0.99
  ckpt_path: './ckpt_gcs/mae_width/d16_h8_convnext/d16_b4096_lr16e-4_h8_DCAEConvNext_30102024_084148/ep_last-checkpoint/0-model.pt'
optimizer:
  type: adamw
  init_lr: 1.6e-3
  weight_decay: 0.0
  betas: [0.9, 0.95]
  max_gn: None
  amp: true
  warmup:
    epoch: 5
    multiplier: 1
    buffer_epoch: 0
    min_lr: 1.0e-4
    decay_end_epoch: 70
    mode: fix
    decay_mode: linear
    start_from_zero: true

experiment:
  batch_size: 32
  accu_step: 1
  epochs: 80
  save_ckpt_freq: 40
  test_freq: 10
  amp: false
  actual_batch_size: 4096