dataset:
  type: imagenet
  transforms:
    type: imagenetDiT256x256

arch:
  stage: 2
  stage_1:
    target: rqvae.models.klvae.Stage1_KLVAE
    params:
      ckpt_path: './ckpt_gcs/model_zoo/klvae/mse'
  stage_2:
    target: rqvae.models.DiT.DiT_Stage2
    params:
      # DiT B/1 Recipe
      hidden_size: 1152
      input_size: 32
      patch_size: 2
      depth: 28
      num_heads: 16
      num_classes: 1000
      cfg: 0.0
      in_channels: 4
      learn_sigma: true
      noise_schedule: 'linear'
      inference_step: 250
  checkpointing: false
  ema: 0.114514
optimizer:
  # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
  type: adamw
  init_lr: 1.0e-4
  weight_decay: 0.0
  betas: [0.9, 0.999]
  max_gn: None
  amp: true
  warmup:
    epoch: 80
    multiplier: 1
    buffer_epoch: 0
    min_lr: 1.0e-4
    mode: fix
    start_from_zero: false

experiment:
  batch_size: 4
  accu_step: 1
  epochs: 80
  save_ckpt_freq: 40
  test_freq: 10
  amp: false
  actual_batch_size: 256

gan:
  disc:
    arch:
      in_channels: 3
      num_layers: 2
      use_actnorm: false
      ndf: 64
      spectral_norm: false
      amp: true
    optimizer:
      # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
      type: adamw
      init_lr: 1.0e-3
      weight_decay: 0.0
      betas: [0.9, 0.95]
      max_gn: None
      warmup:
        epoch: 5  # 5% of total epochs
        multiplier: 1
        buffer_epoch: 0
        min_lr: 0.
        mode: fix
        start_from_zero: true
    experiment:
      test_freq: 1
      amp: false
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: .75
    perceptual_weight: 0.
    disc_start: 100000