_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 5
                - 9
            "12": 0.19.1
            "13": linux-x86_64
base_lr:
    value: 0.0001
batch_size:
    value: 32
beta:
    value: 0.1
checkpoint_path:
    value: null
hidden_dim:
    value: 512
max_grad_norm:
    value: 1
max_steps:
    value: 32000
num_tokens:
    value: 256
num_workers:
    value: 4
perceptual_weight:
    value: 1
resolution:
    value: 256
resume:
    value: false
run_name:
    value: vae_run
sample_steps:
    value: 1000
save_dir:
    value: ckpt_gcs/tokenizer/vae_run_tpu
save_step:
    value: 5000
steps_per_epoch:
    value: 9394
tpu_cores:
    value: 4
tpu_metrics_debug:
    value: false
