dataset:
  type: imagenet
  transforms:
    type: imagenet256x256

arch:
  stage: 1
  stage_1:
    target: rqvae.models.FCMAE.Stage1FCMAE
    params:
      model_name: 'convnextv2_base'
      pretrained_model_path: 'ckpt_gcs/model_zoo/fcmae_b/curated.pt'
  connector:
    target: rqvae.models.connectors.Downsample_with_MLP_Connector
    params:
      hidden_size: 1024
      layers: 8
      bottleneck_ratio: 256
      remove_cls: false
      patch_as_input: true
  checkpointing: false
  ema: 0.114514
optimizer:
  # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
  type: adamw
  init_lr: 7.2e-4
  weight_decay: 0.0
  betas: [0.9, 0.95]
  max_gn: None
  amp: true
  warmup:
    epoch: 5  # 5% of total epochs
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.
    mode: fix
    start_from_zero: true

experiment:
  batch_size: 16
  accu_step: 1
  epochs: 60
  save_ckpt_freq: 30
  test_freq: 1
  amp: false

gan:
  disc:
    arch:
      in_channels: 3
      num_layers: 2
      use_actnorm: false
      ndf: 64
      spectral_norm: false
    optimizer:
      # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
      type: adamw
      init_lr: 1.0e-3
      weight_decay: 0.0
      betas: [0.9, 0.95]
      max_gn: None
      amp: true
      warmup:
        epoch: 5  # 5% of total epochs
        multiplier: 1
        buffer_epoch: 0
        min_lr: 0.
        mode: fix
        start_from_zero: true
    experiment:
      test_freq: 1
      amp: false
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: .75
    perceptual_weight: .01
    disc_start: 100000
    lpips_start: 10