dataset:
  type: imagenet
  transforms:
    type: imagenetDiT256x256
arch:
  stage: 2
  stage_1:
    target: rqvae.models.MAE.Stage1MAEwBottleNeck
    params:
      ckpt_path: ./ckpt_gcs/model_zoo/mae_base_256_ft
      no_cls: true
      mask_ratio: 0.0
      mlp_layers: 6
      bottleneck_ratio: 64
    ckpt_path: ./ckpt_gcs/MAE_bottleneck_r/MAE_bottleneck_pod128/10082024_025041/ep_last-checkpoint/0-model.pt
    checkpointing: false
  stage_2:
    target: rqvae.models.DiT.DiT_Stage2
    params:
      hidden_size: 768
      input_size: 16
      patch_size: 2
      depth: 12
      num_classes: 1000
      in_channels: 12
      noise_schedule: linear
      cfg: 4.0
      #timestep_respacing: 50
    checkpointing: false
  connector:
    target: rqvae.models.connectors.MAE_Diffusion_connector
    params:
      split: 1
  ema: 0.114514
optimizer:
  type: adamw
  init_lr: 0.0002
  weight_decay: 0.0
  betas:
  - 0.9
  - 0.999
  max_gn: None
  amp: true
  warmup:
    epoch: 8
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.0
    mode: fix
    start_from_zero: false
  grad_accm_steps: 1
experiment:
  batch_size: 32
  accu_step: 1
  epochs: 60
  save_ckpt_freq: 30
  test_freq: 5
  amp: false
  total_batch_size: 4096
gan:
  disc:
    arch:
      in_channels: 3
      num_layers: 2
      use_actnorm: false
      ndf: 64
      spectral_norm: false
      amp: true
    optimizer:
      type: adamw
      init_lr: 0.001
      weight_decay: 0.0
      betas:
      - 0.9
      - 0.999
      max_gn: None
      warmup:
        epoch: 5
        multiplier: 1
        buffer_epoch: 0
        min_lr: 0.0
        mode: fix
        start_from_zero: true
    experiment:
      test_freq: 1
      amp: false
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: 0.75
    perceptual_weight: 0.0
    disc_start: 100000
seed: 0
runtime:
  args:
    model_config: /home/bytetriper/VAE-enhanced/configs/imagenet256/stage2/DiTwmaebtnk.yaml
    result_path: /home/bytetriper/VAE-enhanced/ckpt_gcs/aW_DiT_B_2_b4096_lr2e-4_ep60
    load_path: ''
    test_epoch: -1
    postfix: ''
    seed: 0
    world_size: 128
    local_rank: 0
    node_rank: -1
    dist_backend: xla
    timeout: 120
    eval: false
    resume: false
    use_ddp: false
    use_autocast: false
    rank: 0
  extra_config: {}
  distenv:
    world_size: 128
    world_rank: 0
    local_rank: 0
    master: true
    device_name: TPU:0
    TPU: true
    use_ddp: false
result_path: /home/bytetriper/VAE-enhanced/ckpt_gcs/aW_DiT_B_2_b4096_lr2e-4_ep60/DiTwmaebtnk/11082024_230514
load_path: ''
