dataset:
  type: imagenet # overfitting test
  transforms:
    type: imagenetDiT256x256

arch:
  stage: 2
  stage_1:
    target: rqvae.models.MAE.Stage1MAE
    params:
      ckpt_path: './ckpt_gcs/model_zoo/mae_base_256_ft_r'
      no_cls: true
  connector:
    target: rqvae.models.connectors.ReshapeAndSplit_connector
    params:
      split: 1
      remove_cls: true
    ckpt_path: './ckpt_gcs/model_zoo/mae_base_256_ft_r/connector.pt'
  stage_2:
    target: rqvae.models.DiT.DiT_Stage2
    params:
      # DiT B/1 Recipe
      hidden_size: 1024
      input_size: 16
      patch_size: 1
      depth: 12
      num_heads: 16
      num_classes: 1000
      cfg: 0.0
      in_channels: 768
      learn_sigma: true
      noise_schedule: 'linear'
      inference_step: 250
      #do_beta_rescaling: true
  do_normalize: true
  checkpointing: false
  ema: 0.114514 # 337 227 125 606 # 
optimizer:
  # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
  type: adamw
  init_lr: 8.0e-4
  weight_decay: 0.0
  betas: [0.9, 0.95]
  max_gn: None
  amp: true
  warmup:
    epoch: 5  # 5% of total epochs
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.
    mode: fix
    start_from_zero: true

experiment:
  batch_size: 32
  accu_step: 1
  epochs: 80
  save_ckpt_freq: 40
  test_freq: 5
  amp: false
  actual_batch_size: 2048
gan:
  disc:
    arch:
      in_channels: 3
      num_layers: 2
      use_actnorm: false
      ndf: 64
      spectral_norm: false
    optimizer:
      # Original VQ-GAN: lr = 4.5e-06 * (batch size) -> 5.4e-5 for batch size 12
      type: adamw
      init_lr: 1.0e-3
      weight_decay: 0.0
      betas: [0.9, 0.95]
      max_gn: None
      amp: true
      warmup:
        epoch: 5  # 5% of total epochs
        multiplier: 1
        buffer_epoch: 0
        min_lr: 0.
        mode: fix
        start_from_zero: true
    experiment:
      test_freq: 1
      amp: false
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: .75
    perceptual_weight: .01
    disc_start: 100000
    lpips_start: 10