dataset:
  type: imagenet_latent
  transforms:
    type: imagenetDiT256x256

arch:
  stage: 2
  stage_1:
    target: rqvae.models.klvae.Stage1_KLVAE_OnlyDecoder
    params:
      ckpt_path: './ckpt_gcs/model_zoo/klvae/mse'
  stage_2:
    target: rqvae.models.DiT.DiT_Stage2
    params:
      # DiT B/1 Recipe
      hidden_size: 768
      input_size: 32
      patch_size: 2
      depth: 12
      num_heads: 16
      num_classes: 1000
      cfg: 0.0
      in_channels: 4
      learn_sigma: true
      noise_schedule: 'linear'
      inference_step: 250
      n_samples: 1
  checkpointing: false
  ema: 0.9
optimizer:
  type: adamw
  init_lr: 1.6e-3
  weight_decay: 0.0
  betas: [0.9, 0.95]
  max_gn: None
  amp: true
  warmup:
    epoch: 5
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.0
    mode: fix
    decay_mode: linear
    start_from_zero: true


experiment:
  batch_size: 2
  accu_step: 1
  epochs: 80
  save_ckpt_freq: 40
  test_freq: 10
  amp: false
  actual_batch_size: 4096
